module.exports = {
  apps: [{
    name: 'qqbot',
    script: 'src/index.ts',
    interpreter: 'node',
    interpreter_args: '--import tsx/esm',
    cwd: '/home/ubuntu/Magent/claudeqqbot',
    max_restarts: 20,
    restart_delay: 5000,
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    error_file: '/home/ubuntu/Magent/claudeqqbot/logs/error.log',
    out_file: '/home/ubuntu/Magent/claudeqqbot/logs/out.log',
    merge_logs: true,
  }, {
    name: 'progress',
    script: 'tools/progress_server.cjs',
    interpreter: '/usr/local/bin/node',
    cwd: '/home/ubuntu/Magent/claudeqqbot',
    max_restarts: 10,
    restart_delay: 3000,
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    error_file: '/home/ubuntu/Magent/claudeqqbot/logs/progress-error.log',
    out_file: '/home/ubuntu/Magent/claudeqqbot/logs/progress-out.log',
    merge_logs: true,
  }
,
    {
      name: 'reminder-worker',
      script: 'src/reminder/worker/main.cjs',
      interpreter: 'node',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/reminder-worker-error.log',
      out_file: './logs/reminder-worker-out.log',
      merge_logs: true,
      time: true,
    },
]
}
